<?php
/**
 * Created by PhpStorm.
 * User: nzharkov
 * Date: 30.03.2017
 * Time: 18:43
 */

namespace app\api\modules\v1\controllers;


use HttpException;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\auth\QueryParamAuth;
use yii\rest\ActiveController;
use yii\web\BadRequestHttpException;
use yii\web\MethodNotAllowedHttpException;

class AuthController extends ActiveController
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        /*$behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
        ];*/
        return $behaviors;
    }

    private $paramsForActions = [
        'create' => [
            'vk_id',
            'village_name',
        ]
    ];


    public function checkAccess($action, $model = null, $params = [])
    {
        $params = Yii::$app->request->queryParams;
        if (!isset($params['hash'])){
            throw new MethodNotAllowedHttpException("invalid hash");
        }

        $hash = $params['hash'];
        unset($params['hash']);
        ksort($params);
        $s = http_build_query($params,'','&');
        $secretKey = 'qweqwe';
        $crypt = Yii::$app->getSecurity()->hashData($s,$secretKey);
        $data = Yii::$app->getSecurity()->validateData($crypt,$secretKey);
        error_log("crypt: ".$crypt);
        error_log("validate: ".$data);
        if ($hash === $crypt) {
            parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
        }else {
            //throw new BadRequestHttpException('User not found');

        }

        foreach ($params as $key => $param){
            error_log($key."=".$param);
        }

    }


}