<?php
/**
 * Created by PhpStorm.
 * User: nzharkov
 * Date: 30.03.2017
 * Time: 18:43
 */

namespace app\api\modules\v1\controllers;



use Yii;
use yii\filters\ContentNegotiator;
use yii\filters\Cors;
use yii\rest\ActiveController;
use yii\web\BadRequestHttpException;
use yii\web\Response;

class AuthController extends ActiveController
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter' ] = [
            'class' => Cors::className(),
        ];
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        return $behaviors;

    }

    private $paramsForActions = [
        'create' => [
            'vk_id',
            'village_name',
        ]
    ];


    public function checkAccess($action, $model = null, $params = [])
    {
        error_log("checking access");

        if (Yii::$app->request->isOptions){
            throw new BadRequestHttpException("no options");
        }


        $params = Yii::$app->request->queryParams;

        error_log("params:");
        foreach ($params as $key => $param){
            error_log($key."=".$param);
        }

        if (!isset($params['hash'])){
            throw new BadRequestHttpException('no hash - no answer');
        }

        $hash = $params['hash'];
        unset($params['hash']);
        ksort($params);
        $s = http_build_query($params,'','&');
        $secretKey = 'qweqwe';
        $crypt = Yii::$app->getSecurity()->hashData($s,$secretKey);
        error_log("crypt: ".$crypt);
        error_log("hash:  ".$hash);
        if ($hash === $crypt) {
            error_log("correct");
            parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
        }else {
            throw new BadRequestHttpException('invalid hash');
        }
    }


}