<?php

namespace app\api\modules\v1\controllers;

use app\api\modules\v1\models\village\GameModel;
use app\api\modules\v1\models\village\User;
use Exception;
use Yii;


class GameController extends AuthController
{

    public $modelClass = 'app\api\modules\v1\models\village\GameModel';

    public function beforeAction($action)
    {
        //$this->checkAccess($action); // TODO: uncomment this to hash validation
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actions()
    {
        $actions = [];
        return $actions;
    }

    public function actionStart($vk_id)   {
        //$user = (new GameModel())->getUserByVkId($vk_id);
        $user = GameModel::startSession($vk_id);
        if (!$user){
            throw new Exception("not_exist");
        }
        return $user;
    }

    public function actionCreate($vk_id, $village_name){

    }

    public function actionGet ($vk_id)
    {
        $user = User::find()
            ->where(['vk_id' => $vk_id])
            ->one();
        if ($user){
            return $user;
        } else {
            throw new Exception("not_exist");
        }
    }

    public function actionTest (){
        $test = (new GameModel())->test();
    }
}
