<?php

namespace app\api\modules\v1\controllers;

use app\models\village\User;


class UserController extends AuthController
{
    public $modelClass = 'app\models\village\User';
    public function beforeAction($action)
    {
        $this->checkAccess($action);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actions()
    {
        $actions = [];//parent::actions();
        //unset($actions['create']);
        return $actions;
    }

    public function actionCreate($vk_id, $village_name)
    {
        $user = new User();
        $user->VK_ID = $vk_id;
        $user->VILLAGE_NAME = $village_name;



        $isInserted = $user->insert();

        if ($isInserted) {
            return $user;
        }else {
            return $user->errors;
        }
    }
    public function actionGet ($vk_id)
    {
        $user = User::find()
            ->where(['vk_id' => $vk_id])
            ->one();
        if ($user){
            return $user;
        } else {
            return "{'error' : 'notExist'}";
        }
    }
}
