<?php

namespace app\api\modules\v1\controllers;

use app\api\modules\v1\models\village\User;

use Exception;
use Yii;
use yii\web\BadRequestHttpException;


class UserController extends AuthController
{
    public $modelClass = 'app\api\modules\v1\models\village\User';

    public function beforeAction($action)
    {
        error_log("before action");
        $this->checkAccess($action);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actions()
    {
        $actions = [];//parent::actions();
        //$action_view = $actions['view'];
        //$actions = [];
        //$actions['view'] = $action_view;
        //unset($actions['new']);
        return $actions;
    }

    public function actionNew($vk_id, $village_name)
    {
        error_log("action new");
        $user = new User();
        $user->VK_ID = $vk_id;
        $user->VILLAGE_NAME = $village_name;

        $isInserted = $user->insert();

        if ($isInserted) {
            return $user;
        }else {
            throw new \mysqli_sql_exception($user->errors);
        }
    }
    public function actionGet ($vk_id)
    {
        $user = User::find()
            ->where(['vk_id' => $vk_id])
            ->one();
        if ($user){
            return $user;
        } else {
            throw new Exception("not_exist",1);
        }
    }

}
